[build]
  # Build command for the frontend
  command = "npm run build"
  
  # Directory where the build output will be placed
  publish = "dist"
  
  # Base directory for the build
  base = "."

[build.environment]
  # Node.js version to use
  NODE_VERSION = "18"
  
  # Enable CI mode to treat warnings as errors
  CI = "false"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  # Handle client-side routing
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = [""], Country = [""], Language = [""]}

# API proxy to backend (if using Netlify Functions or external backend)
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.com/api/:splat"
  status = 200
  force = true
  
# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:;"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"